#!/bin/sh
echo GTelnet v2.2
echo ----------------------------------------------------------------------------------
echo To run this script you either have to run as root
echo or you have to have a write access to 
echo /usr/share/pixmaps and /usr/share/icons
echo Installing icons background images to /usr/share ...

mkdir -p /usr/share/pixmaps/gtelnet

if [ -f /etc/mandrake-release ];
  then cp -fv share/gtelnet /usr/lib/menu/gtelnet;
fi

echo
echo Copying images and icons...
cp -fv share/*.jpg /usr/share/pixmaps/gtelnet
cp -fv share/*.png /usr/share/pixmaps
cp -fv share/*.xpm /usr/share/icons

echo
echo Copying documentation...
cp -fRv docs /usr/doc/gnome-telnet-2.2

echo
echo Installing the icon to GNOME Menu in /usr/share/gnome/apps/Internet ...
cp -fv share/GTelnet.desktop /usr/share/gnome/apps/Internet

chmod go+rx /usr/share/pixmaps/gtelnet
chmod go+rx /usr/doc/gnome-telnet-2.2

echo ----------------------------------------------------------------------------
echo Done! Have fun! Now to run GTelnet, click it from the "Internet" menu
