/* Automatically generated by po2tbl.sed from gnome-telnet.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"8-bit data path (both output and input)", 2},
  {"8-bit data path on output", 3},
  {"Stop any character from being recognized as an escape character", 4},
  {"\
Forward a forwardable copy of the local credentials to the remote system (if \
Kerberos V5 is used)", 5},
  {"Attempt automatic login", 6},
  {"Specify a user interface similar to rlogin", 7},
  {"Turn on encryption of the data stream", 8},
  {"Set the initial value of the debug flag to TRUE", 9},
  {"Set the initial telnet escape character to:", 10},
  {"Set the IP type-of-service  (TOS)  option  to the value:", 11},
  {"Disable the type of authentication: ", 12},
  {"Request  Kerberos tickets for the remote host in the realm:", 13},
  {"Trace file :", 14},
  {"Redirect input from /dev/null", 15},
  {"Disable authentication agent forwarding", 16},
  {"Disable X11 connection forwarding", 17},
  {"Allocate a tty even if command is given", 18},
  {"Display verbose debugging messages", 19},
  {"Don't allocate a privileged port", 20},
  {"Don't display any warning messages", 21},
  {"Fork into background after authentication", 22},
  {"Enable compression", 23},
  {"Allow remote hosts to connect to local forwarded ports", 24},
  {"Don't request a session", 25},
  {"Set SSH2 debug level to:", 26},
  {"Identity file for public key authentication to:", 27},
  {"Set escape character to:", 28},
  {"\
Select encryption algorithm (For OpenSSH: only '3des' and 'blowfish' are \
supported)", 29},
  {"Allows an eight-bit input data path at all times", 30},
  {"Stops any character from being recognized as an escape character", 31},
  {"Turns off all Kerberos authentication", 32},
  {"Allows the rlogin session to be run in \"litout\" mode", 33},
  {"Turns on socket debugging", 34},
  {"Turns on DES encryption for all data passed via the rlogin session", 35},
  {"Request Kerberos tickets for the remote host in the realm:", 36},
  {"Background Color", 37},
  {"Foreground Color", 38},
  {"Executable Files Color", 39},
  {"Directories Color", 40},
  {"Display Font", 41},
  {"Background Image", 42},
  {"GTelnet", 43},
  {"Select one of the options", 44},
  {" Host name ", 45},
  {" Port ", 46},
  {"port number -- leave blank for default", 47},
  {"Connect", 48},
  {"Connect to the remote host", 49},
  {"Disconnect", 50},
  {"Disconnect from the remote host", 51},
  {"Preferences", 52},
  {"Change your settings", 53},
  {"Help", 54},
  {"Documentation", 55},
  {"Information", 56},
  {"About GTelnet", 57},
  {"Click here for a complete documentation", 58},
  {"\
GTelnet is a frontend for the following programs:\n\
\n\
- Telnet:  to communicate with another host using the TELNET protocol. \n\
\n\
- SSH:  ssh (Secure Shell) is a program for logging into a remote machine \
and for executing commands on a remote machine.  It is intended to replace \
rlogin and rsh, and provide secure encrypted communications between two \
untrusted hosts over an insecure network.  X11 connections and arbitrary \
TCP/IP ports can also be forwarded over the secure channel. (Copied from SSH \
manual)\n\
\n\
- RLogin: rlogin is a program that is a little bit similar to telnet. It is \
intended to make remote administration over local area network easier, but \
it can be very insecure. It is recommended that you use SSH instead of \
rlogin.", 59},
  {"Copyright (C) 2000 the Free Software Foundation", 60},
  {"GTelnet is a frontend to the ole good telnet, ssh, and rlogin", 61},
  {"Authors: ", 62},
  {"Authors", 63},
  {"\
Today, there's a lot of poor children out there who need your help.\n\
\n\
For a dollar a day, you can help change a child's life forever. With your \
sponsorship, you will help provide basic needs like clean water, schools, \
clinics and agricultural training that will lift your sponsored child, \
his/her family, and community - out of poverty.\n\
\n\
If you have the resources available and if you're willing to help those who \
are less fortunate, please sponsor a child.", 64},
  {"For more information, please visit:", 65},
  {"http://www.WorldVision.com", 66},
  {"Please Help Needy Children", 67},
  {"Trace file", 68},
  {"Telnet Options", 69},
  {"SSH Options", 70},
  {"RLogin Options", 71},
  {"Terminal type:", 72},
  {"Display Settings", 73},
  {"SSH Login", 74},
  {"Username:", 75},
  {"\
If you don't want to see this login box, type user@hostname in the host name \
entry, and to restore the previous settings you can click the pulldown \
button next to it to retrieve the history.", 76},
  {"Please fill in the host name :-)", 77},
  {"Not connected", 78},
  {"Couldn't find pixmap file: %s", 79},
  {"Couldn't create pixmap from file: %s", 80},
};

int _msg_tbl_length = 80;
