#ifndef NO_XPM_PLEASE
#define NO_XPM_PLEASE
/* XPM */

static char * gnome_telnet_xpm[] = {
"48 48 312 2",
"  	c None",
". 	c #D7D7CF",
"+ 	c #EFEBDF",
"@ 	c #E7E7DF",
"# 	c #E7E3D7",
"$ 	c #DFDFD7",
"% 	c #DFDBD7",
"& 	c #DFD7CF",
"* 	c #D7D3C7",
"= 	c #D7CFC7",
"- 	c #CFCFC7",
"; 	c #CFCBBE",
"> 	c #CFC7BE",
", 	c #C7C7BE",
"' 	c #C7C3BE",
") 	c #C7BEB6",
"! 	c #BDBDB5",
"~ 	c #BCB8B4",
"{ 	c #BBB7AB",
"] 	c #B6AEA7",
"^ 	c #9B9B94",
"/ 	c #8F8C81",
"( 	c #7D7A76",
"_ 	c #BEBEB6",
": 	c #BEBAB6",
"< 	c #BCB8AC",
"[ 	c #B9B1A9",
"} 	c #AEAEA6",
"| 	c #A9A6A2",
"1 	c #A4A196",
"2 	c #83807C",
"3 	c #B6B2B6",
"4 	c #797979",
"5 	c #717571",
"6 	c #717171",
"7 	c #696D69",
"8 	c #696969",
"9 	c #616561",
"0 	c #616161",
"a 	c #595D59",
"b 	c #595959",
"c 	c #515551",
"d 	c #515151",
"e 	c #494D49",
"f 	c #494949",
"g 	c #484448",
"h 	c #474347",
"i 	c #3E3E3E",
"j 	c #7C7C7C",
"k 	c #A39C95",
"l 	c #918A83",
"m 	c #000000",
"n 	c #8E8E8E",
"o 	c #C7C3C7",
"p 	c #9E9A9E",
"q 	c #969696",
"r 	c #8E8A8E",
"s 	c #868286",
"t 	c #868686",
"u 	c #494549",
"v 	c #3F3F3F",
"w 	c #3E393E",
"x 	c #3C373C",
"y 	c #96938F",
"z 	c #B6B6B6",
"A 	c #E7E7E7",
"B 	c #A6A6A6",
"C 	c #797D79",
"D 	c #404040",
"E 	c #3F3B3F",
"F 	c #3D393D",
"G 	c #343434",
"H 	c #9B9894",
"I 	c #979489",
"J 	c #BEC3BE",
"K 	c #969296",
"L 	c #9E9E9E",
"M 	c #585858",
"N 	c #403B40",
"O 	c #3F3A3F",
"P 	c #353535",
"Q 	c #333333",
"R 	c #9C988D",
"S 	c #909089",
"T 	c #B6BAB6",
"U 	c #414141",
"V 	c #363636",
"W 	c #2C302C",
"X 	c #95958D",
"Y 	c #908D89",
"Z 	c #FFFFFF",
"` 	c #413C41",
" .	c #373737",
"..	c #2D312D",
"+.	c #2C2C2C",
"@.	c #95918D",
"#.	c #8F8C88",
"$.	c #2F332F",
"%.	c #2D2D2D",
"&.	c #94908D",
"*.	c #8F8881",
"=.	c #E7DFD7",
"-.	c #505050",
";.	c #2F2F2F",
">.	c #252825",
",.	c #958D86",
"'.	c #898982",
").	c #383838",
"!.	c #303430",
"~.	c #898682",
"{.	c #272A27",
"].	c #262626",
"^.	c #252525",
"/.	c #272727",
"(.	c #252125",
"_.	c #DFDBCF",
":.	c #303030",
"<.	c #282C28",
"[.	c #272327",
"}.	c #1E1E1E",
"|.	c #1D1D1D",
"1.	c #86837F",
"2.	c #827F7B",
"3.	c #282828",
"4.	c #1F1F1F",
"5.	c #1D1A1D",
"6.	c #827B7B",
"7.	c #7B7B74",
"8.	c #282428",
"9.	c #1F1B1F",
"0.	c #161616",
"a.	c #7E7E77",
"b.	c #7A7773",
"c.	c #202020",
"d.	c #171717",
"e.	c #161216",
"f.	c #7E7A77",
"g.	c #7B7774",
"h.	c #0E0E0E",
"i.	c #7D7976",
"j.	c #797373",
"k.	c #201C20",
"l.	c #171317",
"m.	c #7C7575",
"n.	c #797272",
"o.	c #717971",
"p.	c #848084",
"q.	c #6E6E6E",
"r.	c #807C80",
"s.	c #525252",
"t.	c #0E0A0E",
"u.	c #7B7474",
"v.	c #C6C6BD",
"w.	c #C7C3B6",
"x.	c #959195",
"y.	c #484C48",
"z.	c #484848",
"A.	c #272B27",
"B.	c #0D0A0D",
"C.	c #555955",
"D.	c #7A7373",
"E.	c #787171",
"F.	c #B3AFA3",
"G.	c #C3BFB2",
"H.	c #BABAB2",
"I.	c #BBB7B3",
"J.	c #BAB2AA",
"K.	c #B1B1A9",
"L.	c #B1ADA9",
"M.	c #B0ACA0",
"N.	c #A8A8A0",
"O.	c #A9A5A1",
"P.	c #A9A199",
"Q.	c #A19D99",
"R.	c #A29E9A",
"S.	c #A09991",
"T.	c #999591",
"U.	c #9A9692",
"V.	c #918D8A",
"W.	c #918A8A",
"X.	c #898981",
"Y.	c #87837F",
"Z.	c #85817D",
"`.	c #817A7A",
" +	c #7D7676",
".+	c #767070",
"++	c #64645D",
"@+	c #9B978C",
"#+	c #B2AEAA",
"$+	c #B2AEA3",
"%+	c #A9A9A2",
"&+	c #A8A499",
"*+	c #A7A098",
"=+	c #9F9F98",
"-+	c #AF7B6F",
";+	c #A78A82",
">+	c #A19992",
",+	c #918D82",
"'+	c #A76F68",
")+	c #997C6F",
"!+	c #91918A",
"~+	c #98918A",
"{+	c #9F6B60",
"]+	c #987B6F",
"^+	c #8A8682",
"/+	c #928A8A",
"(+	c #6F6F68",
"_+	c #83837C",
":+	c #899458",
"<+	c #96BB23",
"[+	c #8A9B3F",
"}+	c #766F6F",
"|+	c #726B6B",
"1+	c #5F5F59",
"2+	c #585852",
"3+	c #536B67",
"4+	c #888561",
"5+	c #9D9D96",
"6+	c #9D9A96",
"7+	c #9C988E",
"8+	c #9D968F",
"9+	c #94948D",
"0+	c #96928F",
"a+	c #95928E",
"b+	c #8F8F88",
"c+	c #8E8B87",
"d+	c #8E8780",
"e+	c #888481",
"f+	c #86827F",
"g+	c #888181",
"h+	c #878080",
"i+	c #817D7A",
"j+	c #807D79",
"k+	c #807979",
"l+	c #7A7A73",
"m+	c #75726E",
"n+	c #73706C",
"o+	c #6E6868",
"p+	c #6D6767",
"q+	c #5A5A53",
"r+	c #415252",
"s+	c #415353",
"t+	c #414441",
"u+	c #41413B",
"v+	c #4D4D47",
"w+	c #726F6C",
"x+	c #726D61",
"y+	c #4E4E48",
"z+	c #5C5C55",
"A+	c #79766D",
"B+	c #79796D",
"C+	c #5B5B54",
"D+	c #6C655B",
"E+	c #78786C",
"F+	c #72726C",
"G+	c #55554E",
"H+	c #5C5855",
"I+	c #4E4A48",
"J+	c #53504D",
"K+	c #524F4B",
"L+	c #4B4B45",
"M+	c #52524C",
"N+	c #525652",
"O+	c #69695F",
"P+	c #696259",
"Q+	c #535653",
"R+	c #5F5C52",
"S+	c #706960",
"T+	c #706A6A",
"U+	c #595952",
"V+	c #5D5F57",
"W+	c #515956",
"X+	c #7F7F78",
"Y+	c #85857F",
"Z+	c #938F85",
"`+	c #928B84",
" @	c #8D8D87",
".@	c #8D8986",
"+@	c #8D8B80",
"@@	c #86867F",
"#@	c #878480",
"$@	c #867F79",
"%@	c #7E7C78",
"&@	c #807C79",
"*@	c #7F7979",
"=@	c #797773",
"-@	c #797673",
";@	c #79736D",
">@	c #73736D",
",@	c #6E6C68",
"'@	c #696663",
")@	c #5E5E55",
"!@	c #605F58",
"~@	c #54504C",
"{@	c #596259",
"]@	c #878E87",
"^@	c #8E8E87",
"/@	c #9C998F",
"(@	c #9A938D",
"_@	c #95958F",
":@	c #949287",
"<@	c #969389",
"[@	c #8F8B88",
"}@	c #8E8B80",
"|@	c #898282",
"1@	c #817A73",
"2@	c #797972",
"3@	c #76736F",
"4@	c #6F6B69",
"5@	c #6E6C63",
"6@	c #55514C",
"7@	c #56524E",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                . + + + + + @ @ # # $ $ % & . . * = - ; ; > , ' ) ! ~ { ] ^ / (                 ",
"              . + + + + + @ @ # # $ $ % & . . * - - ; ; > , ' ) _ : < [ } | 1 2                 ",
"              + + 3 4 4 4 4 4 4 5 5 6 7 7 8 9 0 0 a a b b c d e e f g h i j k l m               ",
"              + + 4 n o p q r s t n s 5 5 6 7 7 0 0 0 d e e f u f g g v w x k y m m             ",
"              + + r z A z B s C 4 4 5 5 8 9 9 0 b b b c d e e f u g D E F G H I m m             ",
"              + + 4 B J q t K K 7 C q q q 5 s n C 8 r t L 0 a n b M N O P Q R S m m             ",
"              + @ 4 B T 5 5 s 7 7 8 9 9 0 a a b c c d d e f u u U U N V P W X Y m m             ",
"              @ @ 4 p K t s C n r q Z Z Z a C c c 4 e 0 a u u U ` `  .V ..+.@.#.m m   Z Z       ",
"  Z Z Z Z Z Z # # 4 r n 6 7 7 8 9 9 0 Z Z b c c d d e f u u U ` `  . .$.%.+.&.*.m m m Z Z       ",
"      Z Z     # =.t q K p n 4 q 5 5 s Z Z 4 8 d 5 6 a a b 7 4 9 d -.$.;.%.>.,.'.m m m Z Z       ",
"      Z Z     =.$ 6 Z Z Z Z Z 9 0 a a Z Z c d e e Z Z u Z Z Z ).).!.Z Z Z Z Z ~.m Z Z Z Z Z Z   ",
"      Z Z     $ % Z Z 7 4 9 Z Z a a b Z Z d e e f Z Z Z ` ` Z Z !.Z Z {.].^.Z Z m m m Z Z       ",
"      Z Z     % $ Z Z 8 t 5 Z Z 7 n 8 Z Z 5 0 s a Z Z c 8 d Z Z 0 Z Z /.].(.Z Z m m m Z Z       ",
"      Z Z     _.. Z Z Z Z Z Z Z b c c Z Z e f u u Z Z ` ).).Z Z :.Z Z Z Z Z Z Z m m m Z Z       ",
"      Z Z     . . Z Z 9 0 a a 7 8 8 d Z Z f u u U Z Z ).).!.Z Z <.Z Z [.}.|.1.2.m m m Z Z       ",
"      Z Z     . * Z Z 0 s 7 C 8 8 4 5 Z Z 7 7 b 8 Z Z 0 e f Z Z 3.Z Z 4.}.5.1.6.m m m Z Z       ",
"      Z Z     * = 9 Z Z Z Z Z c d e Z Z Z Z U ` ` Z Z !.:.:.Z Z 3.[.Z Z Z Z Z 7.m m m   Z Z Z   ",
"              = - 0 a a b c c d e e f u u U ` ` ).).!.:.:.<.3.3.8.4.4.9.0.0.a.b.m m m           ",
"              - ; a a b c c d d e f u u U ` ` ).).!.:.:.<.3.3.8.c.4.9.d.0.e.f.g.m m m           ",
"              ; ; a b c c d e e f u u U ` ` ).).!.:.:.<.3.3.8.c.c.9.d.d.e.h.i.j.m m m           ",
"              ; > b c c d d e f u u U ` ` ).).!.:.:.<.3.3.8.c.c.k.d.d.l.h.h.m.n.m m m           ",
"              > , c c r K K s n C p r 4 q 5 s L 6 7 n 8 4 r t o.t p.q.r.s.t.u.n.m m m           ",
"              v.w.x.d y.y.z.g g D N N  . .$.;.;.A././.[.[.4.9.d.0.e.h.h.B.C.D.E.m m m           ",
"              F.G.H.I.{ J.K.L.M.M.N.| O.P.Q.Q.R.S.T.T.U.V.V.V.W.X.Y.Z.`. +D..+++m m m           ",
"                @+#+$+%+%+O.&+*+=+-+;+>+,+'+)+!+~+{+]+^+/+2.(+_+:+<+[+n.}+|+1+2+m m m           ",
"                  3+4+5+5+6+7+8+9+0+a+b+c+c+#.d+e+f+g+h+i+j+k+l+m+n+o+p+q+r+s+m m m m           ",
"                    m m m m t+u+v+w+x+y+z+A+B+C+D+E+F+G+H+z+I+J+m m m m m m m m m m m           ",
"                      m m m K+L+1+1+M+M+1+1+N+1+O+P+Q+R+S+T+U+V+m m m m m m m m m m m           ",
"                    W+X+Y+Z+`+ @.@+@@@#@1.1.$@%@&@*@=@-@b.;@>@,@'@)@!@~@m m m m m m             ",
"                    {@]@^@/@(@_@:@<@^@^@[@}@*.1.e+h+|@j+j+1@2@3@4@5@6@7@m m m m m               ",
"                          m m m m m m m m m m m m m m m m m m m m m m m m m m                   ",
"                            m m m m m m m m m m m m m m m m m m m m m m m                       ",
"                                  m m m m m m m m m m m m m m m                                 ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                ",
"                                                                                                "};
/* XPM */
static char * stoerer_xpm[] = {
"120 120 65 1",
" 	c None",
".	c #FF8D43",
"+	c #E8E8E7",
"@	c #818180",
"#	c #737373",
"$	c #666665",
"%	c #C8C8C8",
"&	c #DEDEDD",
"*	c #5A5A5A",
"=	c #989797",
"-	c #424141",
";	c #FE6908",
">	c #B8B7B6",
",	c #393837",
"'	c #A6A6A6",
")	c #040403",
"!	c #252524",
"~	c #FDFCFB",
"{	c #FFECDE",
"]	c #FFBB8F",
"^	c #FBF3EC",
"/	c #F0F0F0",
"(	c #FFD8BF",
"_	c #FE8230",
":	c #FF7820",
"<	c #A34D15",
"[	c #FECBA6",
"}	c #FFC59F",
"|	c #FE9E5F",
"1	c #58341C",
"2	c #754323",
"3	c #9C7154",
"4	c #FFAA70",
"5	c #FF6000",
"6	c #FE7217",
"7	c #FEA566",
"8	c #FF6F10",
"9	c #FFE2CF",
"0	c #D46E2C",
"a	c #FFB27F",
"b	c #C5570F",
"c	c #F6F6F6",
"d	c #B68463",
"e	c #FEEFE3",
"f	c #FDDCC1",
"g	c #895F44",
"h	c #E86D1C",
"i	c #EB6106",
"j	c #171716",
"k	c #4E4E4E",
"l	c #FFD4B4",
"m	c #FFF5EF",
"n	c #3B2A20",
"o	c #323232",
"p	c #2C2C2C",
"q	c #C0C0BF",
"r	c #9F9F9F",
"s	c #8D8D8D",
"t	c #AFAFAF",
"u	c #FFCFAF",
"v	c #D1D1D1",
"w	c #C16F39",
"x	c #7A6B61",
"y	c #FFFFFF",
"z	c #FF6500",
"zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",
"zyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy~^e99([]]7.66;z555zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",
"zyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy~~mm{{[a|_8;z55zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",
"zyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyme{l4.8;55zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",
"zyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyym9[._z55zzzzzzzzzzzzzzzzzzzzzzzzzz6;zzzzzzzzzz",
"zyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyymeu7:z55zzzzzzzzzzzzzzzzzzzzzz5._5zzzzzzzzz",
"zyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy~{u4:55zzzzzzzzzzzzzzzzzzzz5]|5zzzzzzzzz",
"zyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy~9a.;5zzzzzzzzzzzzzzzzz569}85zzzzzzzz",
"zyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy~^[.;5zzzzzzzzzzzzzz564e9|6zzzzzzzz",
"zyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyymu.85zzzzzzzzzzz584f~c[765zzzzzz",
"zyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyml.;5zzzzzz56.7[{~yy~{[4.8zzzz",
"zyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy^u.z5zzzzz;:.4ley~efa.:;zzzz",
"zyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyye}655zzzz55z.]c^].z55zzzzz",
"zyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy~9|85zzzzzz;.^9_z5zzzzzzz",
"zyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyml:55zzzz589uz5zzzzzzzz",
"zyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy97;5zzz5;f]5zzzzzzzzz",
"zyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyym}65zzzzua5zzzzzzzzz",
"zyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy&>+yyyyy/q&~yyyyyyyyyyccyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy(_5zz5[45zzzzzzzzz",
"zyyyyyyyyyyyyyyyyyyy+v/yyyyyyyy/+yyyyyyyyyyyy@)r~yyyyq)$/y+&+yyyy/&@@~yyyyy~&vcyyyyyyyyyyyyyyyyyyyyyyyye|5554.5zzzzzzzzz",
"zyyyyyyyyyyyyyyyyyyy*jsyyy%vyyc$=yyyyyyyyyyyy@)=~yyyy>)*cy=j*~yy~##-o~yyyyyc$-&yyyyyyyyyyyyyyyyyyyyyyyyym4z5..5zzzzzzzzz",
"zyyyyyyyyyyyyyyyyyyy%)-/y/p*~yvo+~++/yy~c++&/@)=yy/&+t)*cy+j)vyyvo&q%~y+/&~yv%~yy/&&/yy//c+++yyyyyyyyyyyym];::5zzzzzzzzz",
"zyyyyyyyyyyyyyyyyyyy/o)%y%)j&yr$/rk**'~/$--!@@)=y&$pkk)$/y~@)#~yss/kscv**,>c$$&yv*,kkvy>-$$,-%yyyyyyyyyyyy~[65zzzzzzzzzz",
"zyyyyyyyyyyyyyyyyyyy~s)@c#j)'~kt=)>+@)qco)=#rs)'/p)=&@)$/yy&jj/c-++)$c-*&>q/,)&copv&-p/>)*v%p!vyyyyyyyyyyyy~};5zzzzzzzzz",
"zyyyyyyyyyyyyyyyyyyyyv)->ktjk%k%!p/yv)k/-j+~c@)'>)k/yq)$/yy~k)>tk~&j#/-)$q~/,j&t)r~yr)tq)r~y=)=yyyyyyyyyyyyy~};5zzzzzzzz",
"zyyyyyyyyyyyyyyyyyyyy~k)p@/-)osv)o/y&j-+-j&yy#)=s)*~yq)$/yyyq),->y&j*cvo))'c,j&q)'yy')=q)@~yr)ryyyyyyyyyyyyyy~};5zzzzzzz",
"zyyyyyyyyyyyyyyyyyyyyyt))vyr))v/!j/y&)$/-j+yy@)rt)kcyq)$/yyyc-)-cy&j*c/&>jp+-)/~k-cy@)%q)@~y=)ryyyyyyyyyyyyyyy~a5zzzzzzz",
"zyyyyyyyyyyyyyyyyyyyyy+)o~y/j,~y>j@&*j&cp)&yy#)r/*j=v#)*/yyyy')tyy&)$+-'+-*/=)s+%$>s!sct)@~ys)=yyyyyyyyyyyyyyyym75zzzzzz",
"zyyyyyyyyyyyyyyyyyyyyy~#tyy~s'yyy>*$$vycs$+yy'k%yc=-$s*scyyyy/@+yy+*r+@*k#&yc'**##$#>cy%kt~y>k>yyyyyyyyyyyyyyyyy^_5zzzzz",
"zyyyyyyyyyyyyyyyyyyyyyyc~yyyc~yyyycccyyycc~yy~c~yy~/c~c~yyyyyycyyyyc~ycc+cyyyyc/++/cyyy~c~yy~c~yyyyyyyyyyyyyyyyyyf;5zzzz",
"zyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy~};zzzz",
"zyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy~|5zzz",
"zyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy{:5zz",
"zyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy}5zz",
"zyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy~.5z",
"zyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy(;z",
"zyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyym|z",
"zyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyfz",
"zyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy~z",
"zyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyz",
"zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz6_.|a]u9myyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyz",
"zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz;8:_|a}(9myyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyz",
"zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz8_.4[{myyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyz",
"zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz;.4}{yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyz",
"zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz:.}{yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyz",
"zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz8|[myyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyz",
"zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz:a9yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyz",
"zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz8}{ymu.z|]zzzzzzzzzzzzz|]zzzz_(zz:zzzzzzz(_zzzzzzzzzzz679yyyyyyyyyyyyyyyyyyyyyyyyyyyyyz",
"zzzzzzzzzzzzzzzz:6zzzzzzzzzzzzzz:mu:z:|4za(z:{z}|zzzzzzza(zzzz.yz|{zzzzzzzy.zzzzzzzzzzzzz;|(yyyyyyyyyyyyyyyyyyyyyyyyyyyz",
"zzzzzzzzzzzzzz81,x6zzzzzzzzzzzzz(uzzzzzzza(zzzzzzzzzzzzza(zzzz.yzz:zzzzzzzy.zzzzzzzzzzzzzzz;|9yyyyyyyyyyyyyyyyyyyyyyyyyz",
"zzzzzzzzzzzzz;1*$kdzzzzzzzzzzzz8y:zzzzzzza(z]|zz(_z.{y9za(z8u|.yz|]zzamy]zy}{{.zzamm|zzzzzzzz84{yyyyyyyyyyyyyyyyyyyyyyyz",
"zzzzzzzzzzzzz2k*-kk.zzzzzzzzzzz.yzzz8.._za(z(azzy.:m|z.8a(89}z.yza(z.m_z.zy}za9z|{8:m:zzzzzzzzz6]~yyyyyyyyyyyyyyyyyyyyyz",
"zzzzzzzzzzzz2p-*$*k>_;zzzzzzzzz_y8zz_({(za(z(azzy.|9zzzza(}(zz.yza(z}]zzzzy.z.yzu(aa{4zzzzzzzzzzz.(yyyyyyyyyyyyyyyyyyyyz",
"zzzzzzzzzz6g*$@$*@#$ko3|.;zzzzzz{azzzza(za(z(azzy.a(zzzza99}zz.yza(z(azzzzy.z.yzu}...:zzzzzzzzzzzz;amyyyyyyyyyyyyyyyyyyz",
"zzzzzzzzz|-*$$s=*$#sr#**kk_zzzzz.y4zzza(za(zu]z8y._y_zz8a(89}z.yza(z4{8z8zy.z.yz4{8z8:zzzzzzzzzzzzzz_(yyyyyyyyyyyyyyyyyz",
"zzzzzzz;d*ok$$#@=$*#ss*$k$ow;zzzz.{{(9y]za(z.m((y.z]y({.a(z89u.yza(z8(m(mzy.z.yzz({(m_zzzzzzzzzzzzzzz;]~yyyyyyyyyyyyyyyz",
"zzzzzz;1*@$k-k$$@t#*#s$kk#*p3:zzzzz_..zzzzzzz8.zzzzz8.:zzzzzzzzzzzzzzz:.8zzzzzzzzz_.zzzzzzzzzzzzzzzzzzz|eyyyyyyyyyyyyyyz",
"zzzzz82k$s=@**kkk*##$#s-*#o-,$_zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz_(yyyyyyyyyyyyyz",
"zzzz63k*$#@rs''=ss$-kk#@$-jk@*2zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz8[yyyyyyyyyyyyz",
"zzz6x--$#$$$$**$#@##$**#@*#s@$nzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz;]yyyyyyyyyyyz",
"zzz|,#-po-***$$#$kk-k*k-$$,!-kkbzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzayyyyyyyyyyz",
"zz;=$#$*k-o-kk-k-o,-,,-o*#$-j!!1zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz4~yyyyyyyyz",
"zz.*@#*$$#$$@@##*$#s#k*##$**k-p-;zzzzzzzzzz_(zzz]u8z:zzzzzzzzzzzz]|zzzzzzzzzzzzzzzzzzzzzz:z]|zzzzzzzzzzzzzzzzz7~yyyyyyyz",
"zz3!$#$#####ss@s@sss@@#$#*!o-**,_zzzzzzzzzz.yzz|m_zz{|zzzzzzzzzzz(azzzzzzzzzzzzzzzzzzzzz|{z(azzzzzzzzzzzzzzzzzz4yyyyyyyz",
"z;-,$##@#@@@sss@ss=@@@#$*$$o!-*ohzzzzzzzzzz.yz|m_zzz:zzzzzzzzzzzz(azzzzzzzzzzzzzzzzzzzzzz:z(azzzzz|.zzzzzzzzzzzz]yyyyyyz",
"z.!k*$@@@@ss=ss@srssss@@#**-j,kpizzzzzzzzzz.y|y.zzzz(__(]m(:z8}mmmaz_(y(8z]4(m.zzzz.}((||]z(9mm|z|y9(zzzzzzzzzzzz}yyyyyz",
"zwj***#@@@=rr''tr==rrss@$**k-)o,izzzzzzzzzz.ym(zzzzzy..y|z(]z}9:z9az{4z]}z(9:|:zzz:{.49:a(z(u8|y:.y4.zzzzzzzzzzzz89yyyyz",
"z<--k*#@ssr't>>q>''''=s#$$*k-,jj5zzzzzzzzzz.y_m}zzzzy..yzza(zm.zz(a_yaa}mz(azzzzzz.9z8yza(z(azz94zy.zzzzzzzzzzzzzz_myyyz",
"z<,--*#@s=tqv&vv%qq>'=@##$*-kk-jzzzzzzzzzzz.yz_m}zzzy..yzza(zm.zz(a_y....z(azzzzzzz}9{]za(z(azz(azy.zzzzzzzzzzzzzzz7yyyz",
"zwp,-*$@sr>%&//+&vvqt=@#***-k*-nzzzzzzzzzzz.yzz_m}zzy..yzza(z}u8z(azm4zz_z(azzzzzzz(a:zza(z(az_y_zy.z8zzzzzzzzzzzzzz[yyz",
"zw,p,k$@sr%v+///&&vqts@$*****k,nzzzzzzzzzzz.yzzz_m}8y..yzza(z8}yyyaz.m({}z(azzzzzzz({}|za(zum(m]zz]{9.zzzzzzzzzzzzzz:eyz",
"z0,!ok#@sr%&////+&vqts@$*kk**ko2zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz8.:zzzzzzzzzza9.|9]zzzz_.8zzzz__zzzzzzzzzzzzzzzz4yz",
"zh,!ok$@srqv+/++&v%>'@#$*k*$*kpg8zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzuuzzu}zzzzzzzzzzzzzzzzzzzzzzzzzzzzz89z",
"zippo-$#s=t>%%qqq>'=@@#******k,j-3zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz8}mm}8zzzzzzzzzzzzzzzzzzzzzzzzzzzzzz7z",
"zzopo-*#s=rr''r'r=s@@##$$*$kkko*$,zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz8z",
"zz2po-*$#@s==rr=sss@@###$$$*kk-**2zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",
"zz2p,-*$$#@ss=ss@@#@@@@#$$$***k!!gzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",
"zz<o,,k$###@@@@@@@s=s@@#$$$***-#$0zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz|]zzzzzzzzz:zzzzzzzzzzzzzzz|]zzzzzzzzzzzzzzzzzzz",
"zz<o,o-*$#####@@####$*$##****k$#$hzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzza(zzzzzzzz|{zzzzzzzzzzzzzzza(zzzzzzzzzzzzzzzzzzz",
"zzbo,kk-,--*$###$-,,k$$#kkk$*k*-$zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzza(zzzzzzzzz:zzzzzzzzzzzzzzza(zzzzzzzzzzzzzzzzzzz",
"zzio--kk,,!pk*$#*-oj)kpjj,#@*k,#3zzzzzzz.{y]zz]y{.zzzz.{y(8z]|zz(_z.{y9za9uy}zzzzz|]z]]9m4zzzzzza{y{(z_(y(8z]4(m.zzzzzzz",
"zzz,-kjk-oj,,*##$k!rtj*@#rs#*kk#3zzzzzz:y_8(|_y8:.zzzz|:8{4z(azzy.:m|z.8am_8m.zzzza(z(98.y8zzzz|m.z](z{4z]}z(9:|:zzzzzzz",
"zzz2-#,=&)#v,k@s@@s@%=qt==@#kkk*wzzzzzz4{aa(uz9(:zzzzzzz.{az(azzy.|9zzzza(zz(azzzza(z(azzy.zzzzu]zza(_yaa}mz(azzzzzzzzzz",
"zzz2-$$*#s#@$$tvt'qs$#@r>=@#kk$>hzzzzzz49..._z8}m_zzzz_(a9az(azzy.a(zzzza(zz(azzzza(z(azzy.zzzzuazza(_y....z(azzzzzzzzzz",
"zzz<,*@@*k==@@%/%q%&&vvvqs@#*oh0;zzzzzz_y_zz_::z](zzzzuaz(azu]z8y._y_zz8a(zz(azzzza(z(azzy.zzzz|{:za(zm4zz_z(azzzzzzzzzz",
"zzzbok#rt''=@sq&q>%v&+//vr@$*-zzzzzzzzzzam(m|_y(m.zzzza9]m(_.m((y.z]y({.a(zz(azzzza(z(azzy.zzzzzamyy(z.m({}z(azzzzzzzzzz",
"zzzz2k@=t>'s#@q%'=>>q%v&%r#*-gzzzzzzzzzzz:.8zz8.:zzzzzz.::_zz8.zzzzz8.:zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz8.:zzzzzzzzzzzzzz",
"zzzzb-#s''r@#t+c%ss=rrr''@*k-wzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",
"zzzzz1*#ssss=tvvvvs@@*$$$,p--hzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",
"zzzzz<,k**@@##@s##@ss$pp-,,-kzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",
"zzzzzz1o,j###$ko*s===@---,-,kzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",
"zzzzzzb-,k*@@srr'trs@@#*--o,jddwhzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",
"zzzzzzi!jo-#$$sts-*@s@#k-ooo$#=%%x20;zzzzzzzzzzzzzz((((}|zzzzzzzzz:zzzzzzzzzzzzzzzzzzzzzzzz}.zzzz(|zzzzu.zzzzz|]zzzzzzzz",
"zzzzb2j)#t$kkktqq+vr@@$-ooo@='@rrj)j-<;zzzzzzzzzzzzy4..4{uzzzzzzz|{zzzzzzzzzzzzzzzzzzzzzzzza(zzz|y{zzz.m8zzzzza(zzzzzzzz",
"zzb1jj))pqr-k$@>>=$*@#*jj$>rk#&vj)!pjjj2izzzzzzzzzzy.zzz8{azzzzzzz:zz}zzz|.zzzzzzzzzzzzzzzz:y:zz(}y.zz}}zzzzzza(z8]zzzzz",
"<jjjjjj)j#sr$$oj)jk@#kp$@*t=tsqojjj!p!!!!<zzzzzzzzzy.zzzz|9z|]]ya|]z}y(]|y9(z_(y(8z]]9m4zzzzu]z:y:}}z8y_8}y{_za(89m(|zzz",
"!!jjjjjjj!tqq$,**$*k-jk&t=ktv@,)!jjo!pp!!p1izzzzzzzy.zzzz.yzam._.a(84y._.y4.z{4z]}z(98.y8zzz.mz](z.y849z}uz.{za(:}9.:zzz",
"!jj!jjjj!!)!#s=@-!p*#@'$=&@>p)jpjj!!ppp!!!onbzzzzzzy.zzzz.{za(zzza(z.yzzzy.z_yaa}mz(azzy.zzzz{|m|zz{4{|zm}aay_a(za(zzzzz",
"!j!!!jjj!!p!j!$-$t@-k>s-*j)j!,p!jj!pppp!!!p,,izzzzzy.zzzz(aza(zzza(z.yzzzy.z_y....z(azzy.zzzzammzzz4mm8zm4...8a(za(zzzzz",
"!!!!!j!!j!!p,oj))!j!!))opo,o!pp!jj!o!pp!!!p,,<zzzzzy.zz_u98za(zzza(z.yzz8y.z8m4zz_z(azzy.zzzz:y]zzz8y}zzuuzz_za(za(z8zzz",
"o!j!!jj!!!pppp!!!ppo,-,!op!!!!p!jj!o!pp!jp,!o1izzzzyyyy{a8zza(zzza(zz99{z]{9..m({}z(azzy.zzzzzu:zzzz}_zz:{99{za(z:m(uzzz",
"p!j!o!!p!!pp,o,,-,----,,-p!pp!!!j!opj!!jooj!n1bzzzzzzzzzzzzzzzzzzzzzzz.:zz__zz8.:zzzzzzzzzzzzz:zzzzz:zzzzz._zzzzzz8.8zzz",
"ppj!p!!p!!ppopooo,,o,,oo,!j!!!!!j!o!!p!p-!!,,12bzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",
"!!j!!j!ppp!ppoooo,,o,oop!p!!!!!!!po!opp-p!,,,12bzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",
"j!j!p!!ppp!ppoooo,,,,o,p!ppppp!!!pop,!,,jo,o,-2<zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",
"jpj!!p!!!ppp!oopo,o,,,,!!o,ooop!!ppopp,!o,,,,,11zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",
"zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz",
"zyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyz",
"zyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyz",
"zyy----$ryyyyyyyyyyyyyyyyyyy-vyyyyyyyr#y#ryyyyyyyyyyyyyyyyyy---ktyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy-vyyyyyyyyyy#)ryyy@@yyz",
"zyy)sqqs!kyyyyyyyyyyyyyyyyyy)qyyyyyyy@-y-@yyyyyyyyyyyyyyyyyy)sqr)vyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy)qyyyyyyyyytj/yyyy--yyz",
"zyy)qyyy/!@yyyyyyyyyyyyyyyyy)qyyyyyyy@-y-@yyyyyyyyyyyyyyyyyy)qyy-@yyyyy/#yyyyyyyyyyyyyyyyyyyyyyyy)qyyyyyyyyy@-y/#yy--yyz",
"zyy)qyyyyroy-vyv-y#s-jtt!)oy)$!!qyyyy@-y-kojsy#s-jtt!)#yyyyy)qyvjso)!v/oj-r/$)!vy-#!!qy#)!tyt!)oy)$!!qyk)jrv!j$oj-r$$yyz",
"zyy)qyyyyq)y)qyq)y-o&rqjryq/)$y@oyyyy@-y-o/q)/-o&rq)v/-ryyyy)))!@qqykk&$oq&$kyt!y)$y@ov)/&t&jryq/)$y@o/sysj/$oq$oq&@@yyz",
"zyy)qyyyyt!y)qyq)y-@yyroyyyy)qyq)yyyy@-y-@yy)q-@yys!@@-kyyyy)qyyyyy&--y@-yyj$@@)v)qyq)yo-&yroyyyy)qyq)yy/#)y@-y@-yyqqyyz",
"zyy)qyyyy-@y)qyq)y-@yy@-yyyy)qyq)yyyy@-y-@yy)q-@yysoqqqvyyyy)qyyy/k$$-y@-yyjsqqq/)qyq)y/$jv@-yyyy)qyq)y@-@)y@-y@-yy//yyz",
"zyy)qyyvko/yjtyt)y-@yyv)vyy/)qyq)yyyy@-y-@yy)q-@yyv)vyyvyyyy)qyyys-y@-y@-y/kkyyvy)qyq)&&y#-v)vyy/)qyq)v)yq)y@-y@-y///yyz",
"zyy))))!@/yysj-o)y-@yyy#)-!q)qyq)yyyy@-y-@yy)q-@yyy@j-jryyyy)qyyyqj@!!t&j-k&!oo!y)qyq)v)-jty#)-!q)qyq)/j#-)s@-y&j-k$$yyz",
"zyyyyyyyyyyyy&vyyyyyyyyy/q&yyyyyyyyyyyyyyyyyyyyyyyyy&q/yyyyyyyyyyyvv/qyy/q/yyqvyyyyyyyy/q&yyy/q&yyyyyyy&qyq/yyyy/q///yyz",
"zyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyz",
"zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz"};

#endif
